/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.isa.front;

import com.isa.common.ActualCertInfo;
import com.isa.common.FrontCommon;
import com.isa.common.ICommon;
import com.isa.common.ManejadorPaneles;
import com.isa.exception.AppletException;
import com.isa.main.MyTableModel;
import com.isa.token.HandlerToken;
import com.isa.token.Token;
import com.isa.utiles.Utiles;
import com.isa.utiles.UtilesMsg;
import java.awt.Color;
import java.io.IOException;
import java.security.KeyStore;
import java.security.NoSuchAlgorithmException;
import java.security.cert.CertificateException;
import java.security.cert.X509Certificate;
import java.util.ArrayList;
import java.util.Enumeration;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.security.auth.login.LoginException;
import sun.security.pkcs11.wrapper.PKCS11Exception;

/**
 *
 * @author JMiraballes
 */
public class LoginJPanel extends javax.swing.JPanel implements ICommon{

    
    /**
     * Creates new form LoginJPanel
     */
    public LoginJPanel() {
        initComponents();
        msjLogin.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        msjLogin = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Autenticación Token"));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel1.setText("Si desea ver los certificados del token ingrese el pin.");

        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel4.setText("Pin:");

        msjLogin.setText("Mensaje");

        jButton1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jButton1.setText("Aceptar");
        jButton1.setPreferredSize(new java.awt.Dimension(84, 20));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(69, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(msjLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPasswordField1, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE))
                                .addGap(33, 33, 33)))
                        .addGap(65, 65, 65))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(143, 143, 143))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(msjLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(171, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        try{
            String pass = new String( jPasswordField1.getPassword());
            if ( Utiles.isNullOrEmpty(pass)){
                mostrarMensajeError("Debe ingresar el pin del token.");
                return;
            }
            
            HandlerToken handlerToken = ActualCertInfo.getInstance().getHandler();
            ActualCertInfo.getInstance().setPassword( pass );
            
            Token token = handlerToken.getTokenActivo();
            token.login(ActualCertInfo.getInstance().getPassword());
            
            ActualCertInfo.getInstance().setPassword( pass );
            ManejadorPaneles.showPanel(ListaCertsJPanel.class.getName());
            
            
        }
        catch ( IOException ex) {
            
            if (ex.getCause() instanceof LoginException){
                LoginException log = (LoginException) ex.getCause();
                PKCS11Exception pkcs = (PKCS11Exception) log.getCause();
                if ( Utiles.PKCS11_EXCEPTION_CKR_PIN_INCORRECT.equals(pkcs.getMessage())){
                    mostrarMensajeError( UtilesMsg.ERROR_PIN_INCORRECTO );
                }
                if (Utiles.PKCS11_EXCEPTION_CKR_PIN_LEN_RANGE.equals(pkcs.getMessage())){
                    mostrarMensajeError( UtilesMsg.ERROR_PIN_INCORRECTO );
                }                
                if (Utiles.PKCS11_EXCEPTION_CKR_PIN_LOCKED.equals(pkcs.getMessage())){
                    mostrarMensajeError( UtilesMsg.ERROR_TOKEN_BLOQUEADO);
                }
                if (Utiles.PKCS11_EXCEPTION_CKR_TOKEN_NOT_RECOGNIZED.equals(pkcs.getMessage())){
                    mostrarMensajeError(UtilesMsg.ERROR_TOKEN_SIN_IDENTIFICAR);
                }
            }            
            Logger.getLogger(LoginJPanel.class.getName()).log(Level.SEVERE, null, ex);
        } 
        catch (NoSuchAlgorithmException ex) {
            mostrarMensajeError(UtilesMsg.ERROR_AUTH);
            Logger.getLogger(LoginJPanel.class.getName()).log(Level.SEVERE, null, ex);
        } 
        catch (CertificateException ex) {
            mostrarMensajeError(UtilesMsg.ERROR_AUTH);
            Logger.getLogger(LoginJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    
    private void mostrarMensajeError( String mensaje ){
        msjLogin.setText( mensaje );
        msjLogin.setVisible(true);
        msjLogin.setForeground(Color.RED); 
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JLabel msjLogin;
    // End of variables declaration//GEN-END:variables

    @Override
    public void setFrontPanelSize() {
        setSize(FrontCommon.SIZE_WIDTH, FrontCommon.SIZE_HEIGHT);
    }
}
